name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Build Firefox Plugin
        run: |
          npm run build:firefox -- --env build_number=1.0.${{ github.run_number }}
        shell: bash

      - name: Package Firefox
        run: |
          zip -r namida-ff.xpi dist
          rm -rf dist

      - name: Build Chrome Plugin
        run: |
          npm run build:chrome -- --env build_number=1.0.${{ github.run_number }}
        shell: bash

      - name: Package Chrome
        run: |
          zip -r namida-chrome.crx dist
          rm -rf dist
